### ISSUE TITLE
Move `request_is_get` and `RequestType` to safe-nd

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#1003]
1. The `request_is_get` function is being used in more places than just `mock/vault.rs` now (soon it will be used in safe_auth, see comments in https://github.com/maidsafe/safe_client_libs/pull/1001), so it should probably be moved to a common module. The most logical home for it is `request.rs` in safe-nd.
2. This function should be renamed as it is not just about checking if a request is a Get. I'm thinking it should be `Request::get_type` (`type` is reserved and not a valid function name)
3. A `Transaction` variant should be added to `RequestType` and the function modified accordingly.

This is not a priority right now but it would be nice to do eventually.

**Comment by m-cat** [comment]
We should consider also moving these functions from `mock/vault.rs` to safe-nd:

1. `check_is_owner_adata`
1. `check_perms_adata`
1. `check_perms_mdata`

**Comment by nbaksalyar** [comment]
>This is not a priority right now but it would be nice to do eventually.

I'd say let's just do this. :slightly_smiling_face: That's a great idea, and we need it in many places.

**Comment by m-cat** [comment]
Fixed by https://github.com/maidsafe/safe-nd/pull/114 and https://github.com/maidsafe/safe_client_libs/pull/1009.
