### ISSUE TITLE
Bootstrap to multiple Vaults

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#1032]
- Take the connection infos for multiple Vaults from the hardcoded contacts in the config file.
- Use N hardcoded contacts to connect to Vaults. When bootstrapping, make sure we don't drop all connections but instead connect to all Vaults at once (should be sufficient to use `QuicP2p::connect` instead of `QuicP2p::bootstrap`).
- Make sure we pass all peer infos from `ConnectionManager` to `ConnectionGroup` (as a list of Elders).
- The challenge mechanism doesn't need to change.

**Comment by lionel1704** [comment]
Resolved by #1148
