### ISSUE TITLE
Move FFI error codes to FFI modules

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#1055]
Currently, FFI-specific error codes are stored outside of the safe_auth and safe_app FFI modules ([example](https://github.com/maidsafe/safe_client_libs/blob/2468c6012cb0ca5ca4aa2348e76099436a050701/safe_authenticator/src/errors.rs#L29)).

1. These error codes should be moved to the corresponding FFI modules for better separation of concerns (i.e. FFI-specific functionality should not appear outside of FFI modules). Follow [this PR](https://github.com/maidsafe/safe-api/pull/296) as a guide.
2. Separate FFI error types can be implemented, as in that PR.
3. Also, most of the error codes are shared between safe_auth and _app and can actually go into safe_core FFI.

**Comment by peter-wilkins** [comment]
Hi, as you can see I've had a crack at this.

Not sure I've fulfilled point 2: Separate FFI error types can be implemented.

I've only run the mock tests - will look into now to run a network locally.

**Comment by m-cat** [comment]
Thanks for the PR! I'll take a look tomorrow.

> I've only run the mock tests - will look into how to run a network locally.

I don't think that's strictly necessary, this is just a refactor, right? Theoretically the functionality shouldn't change -- just make sure it compiles 🙂
