### ISSUE TITLE
Investigate failure of binary compatibility test

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#1091]
The latest push to master broke the binary compatibility test:

https://travis-ci.com/maidsafe/safe_client_libs/jobs/259338006?utm_medium=notification&utm_source=email

We should investigate whether this is a natural consequence of the Client Keys refactor, or whether we introduced a bug in the refactor which needs to be fixed.

**Comment by lionel1704** [comment]
@m-cat when the version of the crates were updated the CI stopped failing.
Makes sense that the new version isn't expected to be compatible with the old one. But it would be nice to understand how Travis is picking that up.

**Comment by m-cat** [comment]
This test stopped failing after I cleared the cache and allowed a new binary to be built. We lost binary compatibility somewhere amongst all the recent changes and refactors, which is not too surprising.

**Comment by lionel1704** [comment]
Ah so it was a lucky coincidence :smile:

**Comment by m-cat** [comment]
Looks like it's failing again:

https://travis-ci.com/maidsafe/safe_client_libs/jobs/263627008

It seems to be because of the rust_sodium removal, especially since we changed how some things are serialized IIRC. I'm going to clear the cache again, if it breaks again then I'll investigate further.

**Comment by m-cat** [comment]
Looks like it's working again, for now:

https://travis-ci.com/maidsafe/safe_client_libs/pull_requests

**Comment by m-cat** [comment]
Closing as the tests have been working.
