### ISSUE TITLE
Making MAID encryption keys symmetric

### ISSUE THREAD

**Issue by ustulation** [maidsafe/safe_client_libs#174]
If it is the case that `A` should be able to do both - encrypt and decrypt the message, will it not be better to use symmetric encryption alone ? We can store strong random `Key` and `IV` in Session Packet for this. Asymmetric would usually mean that `A` encrypts but no one (including `A`) can then decrypt that except `B`, the intended recipient; so unless we plan on sharing data that way we should always be using symmetric scheme ?

Even for shared directories/data, it means the same thing - all should be able to encrypt and decrypt thus all should know both the key pairs, which again would imply we use only symmetric keys. Only for stuffs like messaging we could use asymmetric keys because it's sort of fire and forget so you don't probably want to decrypt and read what you sent earlier.

**Comment by Fraser999** [comment]
I agree with this.

For dir listings, I don't think we should use a single symmetric key to encrypt all dirs (not sure if that's what you're suggesting).

If we use a different key per dir, the logical place for that to be stored is in the parent dir listing, not the session packet.  In which case, I think we're as well using the old method of creating a symmetric key from the Parent ID and the Dir ID rather than creating a new element (symm key) per dir.  (We also used these two elements to create an obfuscation string which we XORed with the encrypted listing too).

**Comment by ustulation** [comment]
Ah sorry, this got sidetracked; back on it now (unresolved issues start haunting as QA catch up draws closer :-) ) 

> For dir listings, I don't think we should use a single symmetric key to encrypt all dirs (not sure if that's what you're suggesting)

Yes that is what i was suggesting. I don't see any added security in case of method you suggested. Also it incurs extra code and complexity (without justifying that cost) compared to using a symmetric MAID encryption key for all private directories. Leaking MAID in both cases is equally disastrous.

May be I'm overlooking something so could you explain the benefits of **not** using a single symmetric key for all directories ?

**Comment by Fraser999** [comment]
It's not really about security.  The main benefit of using a different symm key per folder is when you want to change a folder from private to shared.  With a single key, we'd need to re-encrypt all subdirs.  With a key per dir, we only need to re-encrypt the root dir of the share.

I think there is still a slight argument to be made on the security front.  If an attacker manages to decrypt a single folder by finding out the symm key used to encrypt it, then he has access to _all_ your folders, whereas with a different key per folder, he can only decrypt subdirs of that.  It's a very slight point though.

I feel the extra code and complexity required is minimal, and we already implemented and tested this in the C++ codebase, so we should be able to copy from that.

**Comment by dirvine** [comment]
On this one guys it's worth as back research looking at SQRL and in particular how to derive a private key from identities such as a directory ID and your own keypair. It may feature in later iterations of this design to allow differing ID's access to dirs etc. so substitute what SQRL does for web url's with dir entries (or SAFE: id's) and you will see what I mean.

**Comment by ustulation** [comment]
Ok .. So just to record it here - as many points raised here seem valid, i'm keeping this issue open. Since it is not a blocker to any task and hence probably not going to be addressed in sprint-5, it will remain open for discussion.

**Comment by ustulation** [comment]
Done. No single global key exists anymore - each MutData is encrypted with information present it's parent.
