### ISSUE TITLE
Binaries to be included with releases

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/safe_client_libs#375]
It would be great if binaries could be included with releases, for linux windows and mac, as well as with and without mock-routing.

I am requesting this because
- <s>I can't get 0.22.0 to pass the tests, either with mock-routing or release, nor to build, which is very frustrating.</s> Needed to update to the latest rust.
- People that just want to build the launcher or demo app shouldn't have to install rust just to build safe_core, they should be able to get the binary from MaidSafe

I know this adds a bit to the release process but it would be extremely useful.

**Comment by ustulation** [comment]
Binaries are always released when test-nets are out. They are [put in the forums](https://safenetforum.org/t/maidsafe-dev-update-march-2-2017-test-12c/12691?u=ustulation) during dev-updates.
