### ISSUE TITLE
Account/session packet consistency

### ISSUE THREAD

**Issue by ustulation** [maidsafe/safe_client_libs#469]
For `dev` branch:

How account is handled in mock vault is currently not consistent with real vault for two reasons:

- accounts start with version 0 and mutations counter 0
- account version is not bumped when the mutation counter is updated

This needs to be made consistent with the way `safe_vault` does it.

**Comment by ustulation** [comment]
cc @madadam

**Comment by nbaksalyar** [comment]
This is not relevant anymore as this issue related to `Structured Data`. Now we handle account packets with `Mutable Data` where this issue does not occur.
