### ISSUE TITLE
Error [E0277] when trying to compile on CentOS7.3

### ISSUE THREAD

**Issue by coreyryanhanson** [maidsafe/safe_client_libs#492]
I've tried everything to compile this including editing version numbers in Cargo.toml but have had no luck at all. Anyone know how to overcome this?

This error occurs on CentOs 7.3
Rust is version 1.17.0
Cargo is version 0.18.0

Building is the only option since the precompiled RPM uses GLIBC 2.18 as a dependency and the OS only supports up to version 2.17

Anyone have any ideas for a solution?

This is the output I got from terminal during the build.
Compiling safe_core v0.23.0 (file:///home/user/directory/safe_client_libs)
     Running `rustc --crate-name safe_core src/lib.rs --crate-type staticlib --crate-type rlib --crate-type cdylib --emit=dep-info,link -C opt-level=3 --cfg 'feature="use-mock-routing"' -C metadata=1399a3d9e82945b6 -C extra-filename=-1399a3d9e82945b6 --out-dir /home/user/directory/safe_client_libs/target/release/deps -L dependency=/home/user/directory/safe_client_libs/target/release/deps --extern chrono=/home/user/directory/safe_client_libs/target/release/deps/libchrono-a0abf83004bdf84c.rlib --extern self_encryption=/home/user/directory/safe_client_libs/target/release/deps/libself_encryption-9122db1b333518cf.rlib --extern routing=/home/user/directory/safe_client_libs/target/release/deps/librouting-be988c54c8b9b16a.rlib --extern lazy_static=/home/user/directory/safe_client_libs/target/release/deps/liblazy_static-d9471cc515b33152.rlib --extern maidsafe_utilities=/home/user/directory/safe_client_libs/target/release/deps/libmaidsafe_utilities-02893d81d75fb4e2.rlib --extern log=/home/user/directory/safe_client_libs/target/release/deps/liblog-99976f5c52edad5f.rlib --extern serde=/home/user/directory/safe_client_libs/target/release/deps/libserde-a92605a8c8496775.rlib --extern serde_derive=/home/user/directory/safe_client_libs/target/release/deps/libserde_derive-1a4d7c5f4a008fa3.so --extern unwrap=/home/user/directory/safe_client_libs/target/release/deps/libunwrap-03dd0d4caab6729d.rlib --extern libc=/home/user/directory/safe_client_libs/target/release/deps/liblibc-a648fee61247746d.rlib --extern config_file_handler=/home/user/directory/safe_client_libs/target/release/deps/libconfig_file_handler-e76a5df7ec5efb96.rlib --extern lru_cache=/home/user/directory/safe_client_libs/target/release/deps/liblru_cache-92bb69dfc97c3127.rlib --extern rand=/home/user/directory/safe_client_libs/target/release/deps/librand-edb078ba7b4b5548.rlib --extern rust_sodium=/home/user/directory/safe_client_libs/target/release/deps/librust_sodium-3d92d7cfc617ad47.rlib -L native=/home/user/directory/safe_client_libs/target/release/build/rust_sodium-sys-93a3925142c8ed36/out/installed/lib -L native=/home/user/directory/safe_client_libs/target/release/build/brotli-sys-4f6c5922c144db5c/out`
error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Serialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:10
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |          ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Serialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:10
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |          ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:21
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::SeqVisitor::visit`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:21
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::SeqVisitor::visit`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:21
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::MapVisitor::visit_value`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:21
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::MapVisitor::visit_value`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:21
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::private::missing_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/file_metadata.rs:21:21
   |
21 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::private::missing_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Serialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:10
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |          ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Serialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:10
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |          ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:21
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::SeqVisitor::visit`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:21
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::SeqVisitor::visit`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:21
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::MapVisitor::visit_value`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:21
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::MapVisitor::visit_value`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:21
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::private::missing_field`

error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: serde::Deserialize` is not satisfied
  --> src/nfs/metadata/directory_metadata.rs:26:21
   |
26 | #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `chrono::DateTime<chrono::UTC>`
   |
   = note: required by `serde::de::private::missing_field`

error: aborting due to 16 previous errors

error: Could not compile `safe_core`.

Caused by:
  process didn't exit successfully: `rustc --crate-name safe_core src/lib.rs --crate-type staticlib --crate-type rlib --crate-type cdylib --emit=dep-info,link -C opt-level=3 --cfg feature="use-mock-routing" -C metadata=1399a3d9e82945b6 -C extra-filename=-1399a3d9e82945b6 --out-dir /home/user/directory/safe_client_libs/target/release/deps -L dependency=/home/user/directory/safe_client_libs/target/release/deps --extern chrono=/home/user/directory/safe_client_libs/target/release/deps/libchrono-a0abf83004bdf84c.rlib --extern self_encryption=/home/user/directory/safe_client_libs/target/release/deps/libself_encryption-9122db1b333518cf.rlib --extern routing=/home/user/directory/safe_client_libs/target/release/deps/librouting-be988c54c8b9b16a.rlib --extern lazy_static=/home/user/directory/safe_client_libs/target/release/deps/liblazy_static-d9471cc515b33152.rlib --extern maidsafe_utilities=/home/user/directory/safe_client_libs/target/release/deps/libmaidsafe_utilities-02893d81d75fb4e2.rlib --extern log=/home/user/directory/safe_client_libs/target/release/deps/liblog-99976f5c52edad5f.rlib --extern serde=/home/user/directory/safe_client_libs/target/release/deps/libserde-a92605a8c8496775.rlib --extern serde_derive=/home/user/directory/safe_client_libs/target/release/deps/libserde_derive-1a4d7c5f4a008fa3.so --extern unwrap=/home/user/directory/safe_client_libs/target/release/deps/libunwrap-03dd0d4caab6729d.rlib --extern libc=/home/user/directory/safe_client_libs/target/release/deps/liblibc-a648fee61247746d.rlib --extern config_file_handler=/home/user/directory/safe_client_libs/target/release/deps/libconfig_file_handler-e76a5df7ec5efb96.rlib --extern lru_cache=/home/user/directory/safe_client_libs/target/release/deps/liblru_cache-92bb69dfc97c3127.rlib --extern rand=/home/user/directory/safe_client_libs/target/release/deps/librand-edb078ba7b4b5548.rlib --extern rust_sodium=/home/user/directory/safe_client_libs/target/release/deps/librust_sodium-3d92d7cfc617ad47.rlib -L native=/home/user/directory/safe_client_libs/target/release/build/rust_sodium-sys-93a3925142c8ed36/out/installed/lib -L native=/home/user/directory/safe_client_libs/target/release/build/brotli-sys-4f6c5922c144db5c/out` (exit code: 101)

**Comment by m-cat** [comment]
Hi, sorry no one ever helped you with this...

I'm going to close this Issue because it pertains to an old Rust version and an unsupported platform. If you have any Issues with the latest Rust version on OSX/Win/Ubuntu, please open a new Issue!
