### ISSUE TITLE
Can't log into Alpha 2

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_client_libs#606]
Not sure if this is the right place to post this, but I'm having problems logging in (Windows 10 and Ubuntu).

Log for a new account:

`D 17-10-27 08:19:54.814118 [safe_authenticator::ffi::ipc ipc.rs:59] **ERRNO: -9** CoreError(Operation forbidden - CoreError::OperationForbidden) T 17-10-27 08:23:18.988822 [safe_authenticator::ffi mod.rs:58] Authenticator - create a client account. T 17-10-27 08:23:18.989823 [safe_core::client mod.rs:242] Creating an account. T 17-10-27 08:23:19.069024 [crust::main::service service.rs:556] Network name: Some("alpha_2") T 17-10-27 08:23:20.076684 [crust::main::service service.rs:82] Event loop started T 17-10-27 08:23:20.077169 [crust::main::config_refresher config_refresher.rs:44] Entered state ConfigRefresher T 17-10-27 08:23:20.077669 [safe_core::client mod.rs:1393] Waiting to get connected to the Network... I 17-10-27 08:23:30.096409 [routing::states::bootstrapping bootstrapping.rs:287] Bootstrapping(5d23aa..) Failed to bootstrap. Terminating. D 17-10-27 08:23:30.096409 [routing::state_machine state_machine.rs:418] State::Bootstrapping(5d23aa..) Terminating state machine T 17-10-27 08:23:30.098412 [crust::common::core core.rs:91] Graceful event loop exit. D 17-10-27 08:23:30.100440 [ffi_utils::catch_unwind catch_unwind.rs:53] **ERRNO: -2000** CoreError(Unexpected error - CoreError::Unexpected::{"Could not connect to the SAFE Network"})`

And for an existing one:
`
D 17-10-27 08:29:06.492452 [safe_authenticator::ffi::ipc ipc.rs:59] **ERRNO: -9** CoreError(Operation forbidden - CoreError::OperationForbidden) T 17-10-27 08:29:17.131296 [safe_authenticator::ffi mod.rs:105] Authenticator - log in a registered client. T 17-10-27 08:29:17.131296 [safe_core::client mod.rs:367] Attempting to log into an acc. T 17-10-27 08:29:17.172085 [safe_core::client mod.rs:377] Creating throw-away routing getter for account packet. T 17-10-27 08:29:17.174587 [crust::main::service service.rs:556] Network name: Some("alpha_2") T 17-10-27 08:29:18.182489 [crust::main::service service.rs:82] Event loop started T 17-10-27 08:29:18.182489 [crust::main::config_refresher config_refresher.rs:44] Entered state ConfigRefresher T 17-10-27 08:29:18.183463 [safe_core::client mod.rs:1393] Waiting to get connected to the Network... E 17-10-27 08:29:25.715950 [crust::main::bootstrap mod.rs:228] Bootstrapper has no active children left - bootstrap has failed I 17-10-27 08:29:25.715950 [routing::states::bootstrapping bootstrapping.rs:287] Bootstrapping(548b58..) Failed to bootstrap. Terminating. D 17-10-27 08:29:25.715950 [routing::state_machine state_machine.rs:418] State::Bootstrapping(548b58..) Terminating state machine T 17-10-27 08:29:25.716928 [crust::common::core core.rs:91] Graceful event loop exit. D 17-10-27 08:29:25.718876 [ffi_utils::catch_unwind catch_unwind.rs:53] **ERRNO: -2000** CoreError(Unexpected error - CoreError::Unexpected::{"Could not connect to the SAFE Network"})`

**Comment by ustulation** [comment]
Thanks for the report - some connectivity issues are getting looked into. It should be working right now, could you pls check

**Comment by JPL1** [comment]
Yes it's all OK now - good work!
