### ISSUE TITLE
Cannot import C header files

### ISSUE THREAD

**Issue by mplorentz** [maidsafe/safe_client_libs#634]
[I'm trying to use the header files](https://forum.safedev.org/t/calling-the-rust-client-libs-from-c/1491) that are generated when building `safe_core`, `safe_app`, and `safe_authenticator` libraries. I'm getting a lot of compiler errors when trying to import (for example) `auto-gen/c-include/safe_core.h`. Most of the errors are for unknown types, because types are being used before they have been declared. But some types, such as `XorName` are not defined anywhere in the header files.

I know use of these files is not really supported, but am I missing something simple?

Steps to reproduce:
* cargo build the safe_core library.
* create a simple C files that imports the safe_core.h header file.
* try to compile the C file.

**Comment by nbaksalyar** [comment]
I have added this issue to JIRA: https://maidsafe.atlassian.net/browse/MAID-2576
Thank you for reporting!

**Comment by mplorentz** [comment]
Thanks so much! I will close this issue since it is now tracked in JIRA.
