### ISSUE TITLE
Default `_pictures` containers not found

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_client_libs#680]
As reported in the forum: https://safenetforum.org/t/apps-and-access-control/26023/66, and as per the list of default containers in the corresponding RFC: https://github.com/maidsafe/rfcs/blob/master/text/0046-new-auth-flow/containers.md#default-containers, it seems that the `_pictures` container is missing and not being created in the accounts, the following error is returned when trying to request permissions for it: `-1002: '_pictures' not found in the access container`

If this container is not supposed to exist, then it'll need to be removed from the RFC and DevHub as well: https://hub.safedev.org/discover

**Comment by nbaksalyar** [comment]
That's is correct, the container is not created by default now:
https://github.com/maidsafe/safe_client_libs/blob/05d5bd1a136b5e19cebaf0d1d61c83621d82b22f/safe_authenticator/src/std_dirs.rs#L24-L30

>If this container is not supposed to exist, then it'll need to be removed from the RFC and DevHub as well
Or maybe rather added to the list of standard containers, what do you think @bochaco?

**Comment by bochaco** [comment]
Yes, I guess the initial intentions were to be part of the default containers, as per the RFC, so why not just add it yes @nbaksalyar

**Comment by m-cat** [comment]
Looks like it used to be missing, then we [added it](https://github.com/maidsafe/safe_client_libs/blob/c8325098632b7d65a45a866efe188e5aa63863d7/safe_core/src/nfs/mod.rs#L50), and now it's missing again :P 

+1 from me @bochaco
