### ISSUE TITLE
Some APIs are not exposed by safe_app when built in debug mode

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#690]
Building `safe_client_libs` in debug mode with mock routing feature, some APIs are not being exposed, e.g. trying to run tests from safe_app_nodejs, the error

```
1000: Failed to load native libraries: Error: Dynamic Symbol Retrieval Error: /home/bochaco/work/bochaco-safe_app_nodejs/src/native/mock/libsafe_app.so: undefined symbol: is_mock_build
```

is thrown, even when built with `cargo build --features "use-mock-routing testing"`.

When the safe_app is built with `--release` this issue goes away.

**Comment by nbaksalyar** [comment]
The same issue is observed in JNI.

The proposed solution is to move the `is_mock_build` function from `safe_core` to `safe_authenticator` and `safe_app`, named as `auth_is_mock_build` and `app_is_mock_build` respectively. This way we can properly separate safe_core into its own module which does not expose any FFI functions.
