### ISSUE TITLE
Create basic Rust bindings for librdf's rasqal

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#702]
We want to bring experimental SPARQL support to SAFE Client Libs & SAFE Vault. It makes sense to reuse existing code and libraries, and the library best suited for our needs is [Rasqal](http://librdf.org/rasqal/) (a part of the [Redland RDF libraries suite](http://librdf.org/), licensed under the Apache license terms). Rasqal is implemeted in C and provides an abstract interface that can be applied to custom storages. The goal is to implement a custom storage based on the SAFE Network data types and reuse the existing query language and query processor code.

* Automatically generate bindings through [rust-bindgen](https://github.com/rust-lang/rust-bindgen) (refer to the [user's guide](https://rust-lang.github.io/rust-bindgen/) as necessary).
* Create a Rust crate exposing all the available API functions and raw structures (similar to rust_sodium-sys). Initial project structure is provided in the [rasqal-rs](https://github.com/nbaksalyar/rasqal-rs) repo. Please use the standard Maidsafe repository template (refer to e.g. [p2p](https://github.com/ustulation/p2p/) or [socket-collection](https://github.com/maidsafe/socket-collection/) for an example).
* It would be nice (but _not_ required) to have automatic compilation of `librasqal`, [similar to `rust_sodium`](https://github.com/maidsafe/rust_sodium/blob/2725d27385dcab1674be762aa9e88b4b9b6b55a3/rust_sodium-sys/build.rs). However, please bear in mind that binary packages are already available in Ubuntu/Debian so you can install them by running `apt install librasqal-dev`. There's also a [Homebrew](https://brewformulas.org/Rasqal) formula for it.
* By _basic bindings_ we mean that we are not creating high-level Rust structures or functions on top of the existing C API. The correspondence should be 1-to-1, and it is fine to have unsafe code for now (we can provide a safer API on top of it when we need it).

**Comment by m-cat** [comment]
Tested and verified Rust bindings are now available at this repository:
https://github.com/m-cat/rasqal-rs
