### ISSUE TITLE
Migrate Jira backlog to GitHub Issues

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#737]
There are a number of Jira tasks that haven't been migrated yet. Moving them over would keep our tasks organized and all in one place. Although the backlog is not our current priority, we could tag Issues and facilitate help from the community.

**Comment by m-cat** [comment]
I just got done migrating a large chunk of the Jira backlog. There are still a few issues hwere I didn't know if they were still valid or not -- we can revisit those on Jira someday.

**Comment by nbaksalyar** [comment]
This should be done by now, I think the rest of Jira tasks are no longer relevant.
