### ISSUE TITLE
Consider adding an LoC badge to the Readme

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#751]
It might be worthwhile to add a Lines of Code (LoC) badge to the Readme. It's not a super meaningful metric in itself but it would signify to people that this is a serious project as we have a significant amount of code.

See https://github.com/Aaronepower/tokei#badges

**Comment by trecement** [comment]
Please see pull request https://github.com/maidsafe/safe_client_libs/pull/754

**Comment by nbaksalyar** [comment]
Fixed now. Thanks!
