### ISSUE TITLE
FFI structs may leak memory

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#770]
There may be memory leaks in our client_libs ffi:
https://github.com/maidsafe/safe_client_libs/blob/master/safe_core/src/ffi/ipc/resp.rs#L148

~The strings in this struct are never freed (see Drop implementations for the other structs in this file).~ [Fixed in #758]

MDataKey.val and MDataValue.content (in the same file) also need to be handled as the pointed-to data is never freed.

Fix these issues and check that all FFI structs in safe_client_libs have a correct Drop defined.

Notes:

* ~We need to consider the caveats about implementing Drop and whether they apply: https://doc.rust-lang.org/1.16.0/nomicon/dropck.html~ Checked, does not apply
* ~We need to make sure that we actually run drop. For example, AuthGranted::clone_from_repr_c takes ownership of a pointer to ffi::AuthGranted and makes a clone, but never explicitly drops the pointed-to struct. Is this a memory leak? Write a short test to check this.~ Checked, see comment below

**Comment by nbaksalyar** [comment]
>For example, AuthGranted::clone_from_repr_c takes ownership of a pointer to ffi::AuthGranted and makes a clone, but never explicitly drops the pointed-to struct

It should not be an explicit drop I believe since drops for `*const T` behave in the same way as drops for `&T`. I.e. if you dereference a pointer to a repr C struct, it should be dropped at the scope exit. But yeah, it's worth to double-check.

**Comment by m-cat** [comment]
Ah, the pointer will be dropped at the end of `clone_from_repr_c` scope, but not the data it points to. But it doesn't matter, since `clone_from_repr_c` just does a clone and not a conversion, so the pointed-to data should still be valid after. In other words, you can make multiple clones of the data, as many times as you want. As long as the pointed-to data is something that correctly implements `Drop`, it will be handled correctly at the end of the caller's scope.

Hope that made sense, will remove this from the OP.

**Comment by nbaksalyar** [comment]
Yes, exactly, and we don't want to do this generally:

> the pointer will be dropped at the end of clone_from_repr_c scope, but not the data it points to

because this data is owned by the caller (e.g. NodeJS program calling our FFI APIs). But we'll drop the data correctly if we own it in Rust.
