### ISSUE TITLE
Provide Rust API for apps management in SAFE Authenticator

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#771]
Currently, `safe_authenticator::ffi::apps` is the only way to access some of high-level functions of the Authenticator. We should move code from that module to Rust functions and change the FFI functions to be thin wrappers around native code.

The new module should provide the following functions:

* Remove a revoked app.

```rust
pub fn remove_revoked_app<S: Into<String>>(
  client: &impl Client,
  app_id: S
) -> impl Future<(), AuthError>
```

(move code from [`auth_rm_revoked_app`](https://github.com/maidsafe/safe_client_libs/blob/93154e0fa8bccad18fd6b26457cd80071092b386/safe_authenticator/src/ffi/apps.rs#L58-L60))

* List revoked apps

```rust
pub fn revoked_apps(
  client: &impl Client
) -> impl Future<Vec<AppExchangeInfo>, AuthError>;
```

(move code from [`auth_revoked_apps`](https://github.com/maidsafe/safe_client_libs/blob/93154e0fa8bccad18fd6b26457cd80071092b386/safe_authenticator/src/ffi/apps.rs#L98-L100))

* List registered apps

```rust
pub fn registered_apps(
  client: &impl Client
) -> impl Future<Vec<RegisteredApp>, AuthError>;
```

(move code from [`auth_registered_apps`](https://github.com/maidsafe/safe_client_libs/blob/93154e0fa8bccad18fd6b26457cd80071092b386/safe_authenticator/src/ffi/apps.rs#L157-L159))

The `RegisteredApp` struct is defined below.

* List apps that have access to a certain Mutable Data object on the network

```
use safe_core::ipc::response::AppAccess;

pub fn apps_accessing_mutable_data(
  client: &impl Client,
  name: XorName,
  type_tag: u64,
) -> impl Future<Vec<AppAccess>, AuthError>
```

(move code from [`auth_apps_accessing_mutable_data`](https://github.com/maidsafe/safe_client_libs/blob/93154e0fa8bccad18fd6b26457cd80071092b386/safe_authenticator/src/ffi/apps.rs#L231-L234)

---

The module should also provide a native struct `RegisteredApp`:

```rust
use safe_core::ipc::req::{AppExchangeInfo, Permission};

struct RegisteredApp {
    /// Unique application identifier
    pub app_info: AppExchangeInfo,
    /// List of containers that this application has access to
    /// Maps from the container name to the set of permissions
    pub containers: BTreeMap<String, BTreeSet<Permission>>,
}
```

the [FFI struct](https://github.com/maidsafe/safe_client_libs/blob/93154e0fa8bccad18fd6b26457cd80071092b386/safe_authenticator/src/ffi/apps.rs#L32-L44) should be a wrapper around it.

**Comment by bochaco** [comment]
In an `Authenticator` Rust API I think we are exposing implementation details by requiring the `Client` object to be passed in, in fact `Client` is from `safe_core`, so as a user of `safe_app`/`safe_autenticator` crate I shouldn't need to depend on `safe_core` at all, I think everything should simply `Auhtenticator` methods, taking the `remove_revoked_apps` as an example:
```rust
pub fn remove_revoked_app<S: Into<String>>(
  &self,
  app_id: S
) -> impl Future<(), AuthError>
```

**Comment by nbaksalyar** [comment]
@bochaco ,

> everything should simply be Auhtenticator methods, taking the remove_revoked_apps as an example

That of course would have been nice, but it's not really possible given the async nature of these operations. If you call such a function, it would return you a `Future` which you still need to execute somehow, and in the current API the only way to do this would be to use `Authenticator::send`, which gets us back to the same place - i.e. it might look like this:
```rust
authenticator.send(|_client| {
  authenticator.remove_revoked_app(app_id)
})
```
which is not very different from
```rust
authenticator.send(|client| {
  apps::remove_revoked_app(client, app_id)
})
```
and just adds a needless level of indirection.

We can make these functions blocking though, but that would defeat the purpose of using futures in the first place.

When we have built-in support for async in Rust, the API will be much simpler to use though.

> in fact `Client` is from `safe_core`

`Client` is not defined only in `safe_core`, it's also a part of the [public Authenticator API](https://github.com/maidsafe/safe_client_libs/blob/93154e0fa8bccad18fd6b26457cd80071092b386/safe_authenticator/src/client.rs#L42-L43), so you don't really need to depend on safe_core in this case. But yeah, on a second thought, these functions don't really need to be generic because we wouldn't want to call them with the `safe_app`'s Client impl. So the first argument can be just `safe_authenticator::AuthClient`.

**Comment by joshuef** [comment]
Speaking super generally here:

I think perhaps the _cleanest_ implementation of an API is what's important here. To define some APIs that can be standardised for how to interact with an authentication instance,

While that not be best in terms of performance. There's nothing stopping a consuming application doing their own async handling / threading or some such.

The important thing should be defining a clear API: `<Arguments>: <Return Value(s)>`.

How that's implemented should be of no concern to the API consumer (be it async or blocking...). Performance comes in for the choice of backend to these _standardised_ apis. 

So while it may be blocking now. Another implementation may not be. Or some _other_ implementation may be more performant. But the important part should be this simple/clear API contract, which means you _can_ swap implementations.
