### ISSUE TITLE
The NFS `file_open` doesn't support creating a file without passing empty File struct

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#783]
In order to create a new NFS file, the `file_open` function doesn't support receiving a `null` as the File struct param, it requires the client to crate and empty File struct for such purpose. It's herein proposed to support receiving a `null` param so the client doesn't need to bother with creating an empty File struct.

**Comment by sprucely** [comment]
Thinking of taking this on. If the ffi File is null, that means there is no length or capacity information for user_metadata. So when initializing a native File, does that mean its user_metadata should be initialized to an empty Vec<u8> with 0 capacity? Should the into_repr_c() in native File also be modified to set user_metadata_ptr to null when it encounters an empty Vec<u8> with 0 capacity? I could see a client developer easily making the mistake of only checking if user_metadata_ptr is not null while ignoring len and cap, and then trying to dereference it.

**Comment by m-cat** [comment]
> Thinking of taking this on.

Awesome! Thank you for the assistance, and great questions! 

> If the ffi File is null, that means there is no length or capacity information for user_metadata. So when initializing a native File, does that mean its user_metadata should be initialized to an empty Vec with 0 capacity?

I would say so; simply `Vec::new()` would suffice. This field is information provided by the user, and if he wishes to fill it out, he can always create his own file. So in the case where he does not provide a file, just initialize it to an empty vec. I would thoroughly document these behaviors and assumptions in the doc-string for this function.

> Should the into_repr_c() in native File also be modified to set user_metadata_ptr to null when it encounters an empty Vec with 0 capacity? I could see a client developer easily making the mistake of only checking if user_metadata_ptr is not null while ignoring len and cap, and then trying to dereference it.

I don't see any need to modify this function. There is nothing (in this case) wrong with dereferencing a non-null pointer - a properly-written client-side function will just see an empty vec of length 0.

**Comment by sprucely** [comment]
OK. I'm finding some good info in the wiki, but I want to make sure I'm clear on the difference between File::user_metadata and the user_data param in fn file_open(). My guess is that user_metadata gets stored with the file bytes, while user_data is simply passed to the callback as an alternative to closures for languages that don't support closures?

**Comment by m-cat** [comment]
Yeah, that's pretty much right. Our FFI directly targets the C language which doesn't have closures at all, so `user_data` is meant to hold data that can be referenced by the `o_cb` callback function. The wiki goes into it in more detail [here](https://github.com/maidsafe/safe_client_libs/wiki/FFI-calling-conventions#what-is-user_data-and-opaquectx). Long story short, you don't have to worry about `user_data` for the purposes of your PR. 

If you have any ideas about how to make this less confusing, like renaming the `user_metadata` parameter, we're open to suggestions. You could write a comment in the code explaining these two variables, if there's a relevant place for it and if you're up for that.

**Comment by sprucely** [comment]
So I have the change implemented and updated the open_file test to pass a null. Before I clean things up and submit a PR, I'm curious about this snippet in open_file...

```Rust
    let written_file: NativeFile = unsafe {
        unwrap!(call_0(|ud, cb| file_write(
            &app,
            write_h,
            content.as_ptr(),
            content.len(),
            ud,
            cb
        )));
        unwrap!(call_1(|ud, cb| file_close(&app, write_h, ud, cb)))
    };
```

How is it getting a NativeFile from a call to a ffi function? I've looked at the ffi pages in the wiki and looked through the call_... functions, but I don't see anything that actually calls clone_from_repr_c() on the ReprC trait.

**Comment by m-cat** [comment]
Hey, I just got back from a short vacation today. `clone_from_repr_c` is called in `callback_1` in our `ffi_utils` crate:

```rust
extern "C" fn callback_1<E, T>(user_data: *mut c_void, res: *const FfiResult, arg: T::C)
where
    E: Debug,
    T: ReprC<Error = E>,
{
    unsafe {
        let result: Result<T, i32> = if (*res).error_code == 0 {
            Ok(unwrap!(T::clone_from_repr_c(arg)))
        } else {
            Err((*res).error_code)
        };
        send_via_user_data(user_data, SendWrapper(result));
    }
}
```

As you can see, `T` must implement the `ReprC` trait. `callback_1` is in turn called by `call_1`.

I apologize that you couldn't find this information in the wiki -- it should be more clear. Thanks for the feedback!
