### ISSUE TITLE
Add logic for releasing FileContextHandle without closing the file

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#785]
This was reported by frontend:

> It's not possible to free/release a `FileContext` object without closing it so the client is forced to either store the file that was created or leak the `FileContext` object.
>This is to cover scenarios where the client has some logic to cancel/discard a file that was opened but for some reason/logic it's not desired to be stored anymore.

In other words: a `FileContextHandle` can only be free'd by calling `file_close`, but the files operations can be canceled, in which case `file_close` won't be called (as it would save the file to the network). This would result in leaking `FileContextHandle` as it is never freed.

**Comment by sprucely** [comment]
I'm thinking of making a fn for this with a signature and body pretty similar to file_close...
```Rust
#[no_mangle]
pub unsafe extern "C" fn file_cancel(
    app: *const App,
    file_h: FileContextHandle,
    user_data: *mut c_void,
    o_cb: extern "C" fn(user_data: *mut c_void, result: *const FfiResult, file: *const File),
)  {
    catch_unwind_cb(user_data, o_cb, || {
        let user_data = OpaqueCtx(user_data);

        (*app).send(move |_client, context| {
            let file_ctx = try_cb!(context.object_cache().remove_file(file_h), user_data, o_cb);

            o_cb(
                user_data.0,
                FFI_RESULT_OK,
                &file_ctx.original_file.into_repr_c(),
            );
            None
        })
    })
}
```
I thought of removing the file parameter from the callback, but I think it could be helpful to keep it in case the client wants to do something further with the file after cancelling an operation. I haven't yet looked at the api for `file_ctx.writer`, so I'm not sure yet if anything needs to be done to clean it up without actually calling close() on it.

**Comment by m-cat** [comment]
Hey @sprucely, thanks for taking this! Looks great, and I agree that keeping the function similar to `file_close` makes sense. So keeping the file parameter in the callback is something I agree with. 

> I haven't yet looked at the api for file_ctx.writer, so I'm not sure yet if anything needs to be done to clean it up without actually calling close() on it.

Nope, dropping the file context is enough to clean it and its contents up without causing a leak.

One note: in the documentation for this function, I would emphasize that this function should be limited as much as possible, as opening a file incurs a network GET, so cancelling the file operations would be wasteful. It should only be used in rare scenarios.

**Comment by m-cat** [comment]
Closed in https://github.com/maidsafe/safe_client_libs/pull/925.
