### ISSUE TITLE
Expose the `access_container` module as public

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#801]
1. SAFE Authenticator should expose this module as public:
https://github.com/maidsafe/safe_client_libs/blob/67aee98f92d23892b331b47107977020212fe835/safe_authenticator/src/lib.rs#L99
2. All functions in the module should be publicly available (no change here).
3. Please also see if we need to address this TODO item and write a test case for it if needed:
https://github.com/maidsafe/safe_client_libs/blob/67aee98f92d23892b331b47107977020212fe835/safe_authenticator/src/access_container.rs#L202
(It refers to the `authenticator` entry in the access container:)
https://github.com/maidsafe/safe_client_libs/blob/67aee98f92d23892b331b47107977020212fe835/safe_authenticator/src/access_container.rs#L26

**Comment by lionel1704** [comment]
I don't see the need for the access container API to be publicly accessible. The functions in this module can access and manipulate the access container directly. Any authenticator application written in Rust or not should not be able to access this API.

**Comment by bochaco** [comment]
Just in case it helps, I think we needed the access_container function to be able to provide an authorisation for containers, in which case the access container is updated. You can check the implementation we currently have in safe_auth CLI for this here: https://github.com/maidsafe/safe-authenticator-cli/blob/master/src/lib.rs#L570

**Comment by lionel1704** [comment]
Sorry I missed this earlier @bochaco. Indeed, the access_container mod is being used. But it would be better to have native rust functions for each of the functions that performs the required operations for shared_md / additional containers / authentication and encodes the required response. With these functions publicly exposed we can still have functions to perform all the required actions _without_ exposing API to _directly_ manipulate the access_container.
If this makes sense, I can update the issue description accordingly.

**Comment by nbaksalyar** [comment]
This task should be reopened in the `Fixes for safe-cli and Vault integration` project with the description @lionel1704 provided above.
