### ISSUE TITLE
Cleanup clippy rules

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#804]
The [clippy lint rules](https://github.com/maidsafe/safe_client_libs/blob/12ed1b1486c67a24213d50e2b8e11f9d6fe61137/safe_app/src/lib.rs#L61-L73) don't have to be set in `#![cfg_attr(..)]` anymore. Instead, we can put them in the usual `#![allow(...)]` and `#![deny(...)]` attributes along with rustc rules (e.g.: `#[allow(box_pointers, clippy::too_many_arguments, ...)]`).

This change could simplify code in [safe_core](https://github.com/maidsafe/safe_client_libs/blob/12ed1b1486c67a24213d50e2b8e11f9d6fe61137/safe_core/src/lib.rs#L66-L78), [safe_authenticator](https://github.com/maidsafe/safe_client_libs/blob/12ed1b1486c67a24213d50e2b8e11f9d6fe61137/safe_authenticator/src/lib.rs#L58-L70), and [safe_app](https://github.com/maidsafe/safe_client_libs/blob/12ed1b1486c67a24213d50e2b8e11f9d6fe61137/safe_app/src/lib.rs#L61-L73) a little bit.

**Comment by m-cat** [comment]
This was fixed, this issue should have been closed automatically.
