### ISSUE TITLE
Add documentation badges in Readme

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#805]
The [Readme file in the root](https://github.com/maidsafe/safe_client_libs/blob/master/README.md) lacks badges with links to documentation: a reader has to check the readme files in sub-directiores, which is not apparent.

We can add badges for all 3 projects (safe_core, safe_authenticator, and safe_app) in the root, and also remove the "Issues" (`waffle`) badge which is not used.

**Comment by willief** [comment]
Please see PR

**Comment by willief** [comment]
willief aka southside

**Comment by nbaksalyar** [comment]
Closed via #865
