### ISSUE TITLE
Move ImmutableData definition from Routing into safe_nd

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#809]
* Published `ImmutableData` should be defined as part of the `safe-nd` crate.
* All tests related to `ImmutableData` should be moved too.

**Comment by m-cat** [comment]
Update: this PR is waiting on https://github.com/maidsafe/routing/pull/1646 which is waiting on a new version of safe-nd to be published.

**Comment by nbaksalyar** [comment]
Actually, we don't need to wait for the Routing PR.
It's fine to leave the old definition there at the moment.
Thanks @m-cat!
