### ISSUE TITLE
Implement delete Mutable Data RPC

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#811]
Now that the `MutableData` type is implied to be unpublished, RPC to delete sequenced/unsequenced MutableData objects becomes available.

- New method should be added to the `Client` trait:
```rust
pub fn delete_mdata(&self, ref: MutableDataRef, kind: MutableDataKind) -> Box<CoreFuture<()>>;
```
- Implement the delete RPC and functions in mock routing.
- Implement the delete operation logic in mock vault.
- Implement tests:
  - Try to delete `MutableData` as a non-owner. The request should fail with `ClientError::AccessDenied`.
  - Try to delete `SequencedMutableData` as an owner. The request should succeed. Subsequent GET requests should fail with `ClientError::NoSuchData`.
  - Try to delete `UnsequencedMutableData` as an owner. The request should succeed. Subsequent GET requests should fail with `ClientError::NoSuchData`.

**Comment by lionel1704** [comment]
Merged into experimental in #836
