### ISSUE TITLE
Implement unsequenced MutableData semantics

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#812]
- Implement the logic required for unsequenced MutableData in the `safe-nd` data type definition.
- It should have the same APIs as sequenced `MutableData` but without the requirement to set versions when mutating MD contents.
- Implement tests for entries mutation.
  - Verify that it's possible to overwrite entries without having to set an explicit version.
  - Verify that it's possible to delete entries without having to set an explicit version.

Reuse code from the [reference `MutableData` implementation](https://github.com/maidsafe/routing/blob/ba977bd494b69269481e47d61372b394de8a0885/src/data/mutable_data.rs) where needed.

**Comment by lionel1704** [comment]
Structure implemented by maidsafe/safe-nd#3 and maidsafe/safe-nd#8.
Tests should be written for the structure i.e. indepdendent of SCL
