### ISSUE TITLE
Move MutableData implementation from Routing to safe-nd

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#813]
Currently, [sequenced MutableData is implemented](https://github.com/maidsafe/routing/blob/ba977bd494b69269481e47d61372b394de8a0885/src/data/mutable_data.rs) as a part of the Routing crate. We should move this implementation along with the tests into the `safe-nd` crate instead.

**Comment by lionel1704** [comment]
Merged into safe-nd/master via pull requests:
- maidsafe/safe-nd#3
- maidsafe/safe-nd#8
- maidsafe/safe-nd#10
- maidsafe/safe-nd#13
