### ISSUE TITLE
Improve `MDataInfo` struct to account for changes in Mutable Data

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#814]
- `MDataInfo` struct and API have to be changed to accommodate for unsequenced and sequenced MD types. The structure itself should include a type of MutableData being referenced:
```rust
use safe_nd::MutableDataKind;

pub struct MDataInfo {
    /// Name of the data where the directory is stored.
    pub name: XorName,
    /// Type tag of the data where the directory is stored.
    pub type_tag: u64,
    /// Kind of Mutable Data that this structure references.
    pub md_kind: MutableDataKind,
    ...
}
```
- The FFI counterpart of `MDataInfo` should also include the change:
```rust
/// FFI wrapper for `MDataInfo`.
#[repr(C)]
#[derive(Clone)]
pub struct MDataInfo {
    /// Name of the mutable data.
    pub name: XorNameArray,
    /// Type tag of the mutable data.
    pub type_tag: u64,
    /// Kind of Mutable Data that this structure references.
    pub md_kind: MutableDataKind,
    ...
}

/// FFI version of MutableDataKind
#[repr(C)]
pub enum MutableDataKind {
    Unsequenced,
    Sequenced
}
```

- Change the FFI API (in `safe_app::ffi::mdata_infof`) accordingly:
    - In `mdata_info_new_private`: after `type_tag` add a new argument, `md_kind: ffi::MutableDataKind`. Use it to fill in the `MDataInfo` struct.
    - In `mdata_info_random_public`: after `type_tag` add a new argument, `md_kind: ffi::MutableDataKind`. Use it to fill in the `MDataInfo` struct.
    - In `mdata_info_random_private`: after `type_tag` add a new argument, `md_kind: ffi::MutableDataKind`. Use it to fill in the `MDataInfo` struct.
    - `mdata_info_encrypt_entry_key`, `mdata_info_encrypt_entry_value`, `mdata_info_decrypt`, `mdata_info_serialise`, `mdata_info_deserialise` remain unchanged.

- Update tests in the FFI module: 
    - Using the FFI API, create an unsequenced MDataInfo. Verify that the `md_kind` field of the returned `MDataInfo` struct is equal to `MutableDataKind::Unsequenced`. Repeat the same for `create_random_*` functions.
    - Using the FFI API, create a sequenced MDataInfo. Verify that the `md_kind` field of the returned `MDataInfo` struct is equal to `MutableDataKind::Sequenced`. Repeat the same for `create_random_*` functions.

**Comment by lionel1704** [comment]
Resolved in #905
