### ISSUE TITLE
Jenkins Build Should Build New Container on Version Update Builds

### ISSUE THREAD

**Issue by jacderida** [maidsafe/safe_client_libs#816]
The `safe-client-libs-build` container that's used during the build process for SCL is versioned alongside the application. Therefore, when a version change build is triggered, at the end of the process we need to construct a new container with that version.

This will probably be a separate job or pipeline to be triggered, because it will take a significant amount of time to construct the container, and we don't want that to delay the time of the build.

**Comment by lionel1704** [comment]
This  has been resolved.
