### ISSUE TITLE
Simplify permissions handling for MutableData

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#823]
- Currently, we have tri-state permissions, `allow / deny / default`, which are represented by `Option<bool>` (`None` being the `default`). It is required because we can set permissions for `User::Anyone` which would be the fallback for public data - e.g. if we have permissions `[User::Anyone => { Action::Insert => Some(true) }]` we can explicitly deny the insertion operation for `A` as `User::Key(A) => { Action::Insert => Some(false) }`.
- Because `MutableData` becomes unpublished, now we don't have `User::Anyone` (we can't define permissions for an unlimited number of users), and hence we don't need this way of handling permissions either. The [`PermissionSet`](https://github.com/maidsafe/routing/blob/ba977bd494b69269481e47d61372b394de8a0885/src/data/mutable_data.rs#L80) struct can be simplified to deal with binary state `allow / deny`, so we can just use `bool`s instead.

**Comment by lionel1704** [comment]
Resolved by maidsafe/safe-nd#26 and #836
