### ISSUE TITLE
Use UnpubSeqMutableData for the access container

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#824]
- Replace legacy `MutableData` being used in the `safe_authenticator::access_container` module with unpublished sequenced MutableData.
- Reimplement `safe_authenticator::std_dirs::create_access_container` in terms of unpublished sequenced MutableData. Currently, it uses the `create_dir` function from the `safe_core::nfs::dir` module, but ignore that function and don't change it yet - it's better to inline the MD creation procedure in the `create_access_container` function itself for now.
- For `safe_authenticator::access_container::delete_entry` make sure we correctly handle the 'proper' deletion (i.e. removal of the entry instead of blanking it).

**Comment by m-cat** [comment]
>     * For `safe_authenticator::access_container::delete_entry` make sure we correctly handle the 'proper' deletion (i.e. removal of the entry instead of blanking it).

Finally! Very exciting 😄

**Comment by Yoga07** [comment]
Resolved in maidsafe/safe_client_libs#960
