### ISSUE TITLE
Implement Mock Unpublished Mutable Data

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_client_libs#825]
Implement the required functions for the new unpublished mutable data type in the Client trait. Some of the functions can be shared between the `Sequenced` and `Unsequenced` mutable data types. For eg. functions that work with the MData shell

Write separate functions for the RPCs that manipulate the data field.

**Comment by nbaksalyar** [comment]
This is done and merged in the `experimental` branch now.
