### ISSUE TITLE
Revamp permissions handling for Mutable Data

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#827]
Currently, we have a `requester` field for the requests that require permissions check. It might have been an app's public key, or an owner's public key - in the latter case all actions were allowed (including the permissions change).

However, this worked only because we didn't support multisig and multiple ownership. Now that we're switching to use BLS, we have multisig 'for free' (i.e. we can use the same `threshold_crypto::Signature` struct both for a single signature and for multiple signatures). This requires us to change the way we handle the permissions. First, we need to change the `requester` field in request variants to be an enum instead of `safe_crypto::PublicKey`:
```rust
use threshold_crypto::{Signature, PublicKey};

#[derive(Clone, Serialize, Deserialize, PartialEq, PartialOrd, Ord, Eq, Hash)]
pub enum Requester {
    Owner(Signature),
    Key(PublicKey),
}
```

Next, we'll need to decouple the permissions checking from the data types.
Currently, the general pattern we use is the following:
```rust
impl MutableData {
  fn do_permissioned_action(&self, requester: PublicKey) -> Result<(), Error> {
    if self.is_allowed(&requester) {
      // do the action
    } else {
      Err(Error::AccessDenied)
    }
  }
}
```

Now, because the requirement of checking a signature of `Requester::Owner` would complicate both the API and the implementation, it's better to check the permissions in a separate function, e.g. in pseudocode:

```rust
pub fn is_allowed(data: impl MutableData, request: crate::Request, requester: crate::Requester) -> Result<bool, Error> {
  match request {
    Request::ChangeMDataOwnership(..) => Ok(is_owner(data, requester)),
    Request::MutateMData(..) => Ok(is_owner(data, requester) || data.get_user_permissions(requester).is_allowed(Action::Mutate)),
    // and so on
    other_req => Err(Error::InvalidRequest),
  }
}
```
Thus it becomes the responsibility of Vaults (mock and real) to check the permissions before executing a user's request.

**Comment by lionel1704** [comment]
Merged into experimental in #836
