### ISSUE TITLE
SeqMD/UnSeqMD don't accept SeqEntryActions/UnSeqEntryActions for mutations

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_client_libs#841]
On SCL (`experimental` branch), `mutate_seq_mdata_entries` and `mutate_unseq_entries` expect arg `actions: BTreeMap<Vec<u8>, SeqEntryAction>` instead of `SeqEntryActions`/`UnSeqEntryActions` respectively.

Also, the `SeqEntryActions` and `UnSeqEntryActions` don't have a constructor in `safe-nd` so it cannot be used for creating a mutation object and therefore its `ins`, `update`, etc. methods cannot be used for mutating SeqMD/UnSeqMD.
E.g. we are forced to do the following:
```rust
let mut entry_actions: BTreeMap<Vec<u8>, SeqEntryAction> = Default::default();
let _ = entry_actions.insert(
     key.to_vec(),
     SeqEntryAction::Update(Value::new(value.to_vec(), version)),
);
...
client.mutate_seq_mdata_entries(xorname, tag, entry_actions.clone())
```
Ideally this should be possible instead:
```rust
let mut entry_actions = SeqEntryActions::new();
let _ = entry_actions.ins(
     key.to_vec(),
     value.to_vec(), version),
);
...
client.mutate_seq_mdata_entries(xorname, tag, &entry_actions)
```

**Comment by Yoga07** [comment]
Resolved in  maidsafe/safe-nd#46
