### ISSUE TITLE
Client function `get_seq_mdata_value` panics when trying to fetch a non-existing entry

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_client_libs#842]
In `experimental` branch, client function `get_seq_mdata_value` panics when trying to fetch a non-existing entry. Looking at the code the problem seems to be an `unwrap` here: https://github.com/maidsafe/safe_client_libs/blob/experimental/safe_core/src/client/mock/vault.rs#L532

**Comment by lionel1704** [comment]
Merged into experimental in #871
