### ISSUE TITLE
It's not possible to get the balance from a CoinBalance different than the default owned by the account

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_client_libs#843]
In `experimental` branch, It's not possible to get the balance from a `CoinBalance` different than the default owned by the account since the `get_balance` is missing an SK arg for arbitrary `CoinBalance` retrieval:
`fn get_balance(&self, destination: XorName) -> Box<CoreFuture<Coins>>`

https://github.com/maidsafe/safe_client_libs/blob/20b945dc6fc7b8684fd15fde78948240db86503d/safe_core/src/client/mod.rs#L299

**Comment by lionel1704** [comment]
Merged into experimental in #871
