### ISSUE TITLE
Adapt SCL to changes in safe-nd API

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#849]
1. Modules like `request` and `response` in safe-nd has been made private now.
2. There are also several renamed request/response types.
3. Most of the `Request` enum variants now comprise of a single inline tuple rather than an inline struct (e.g. `GetMDataShell(Address)` instead of `GetMDataShell { address: Address }`).
4. Several structs have been refactored and renamed (e.g. `MutableDataRef` -> `Address`, etc.).

**Comment by lionel1704** [comment]
Resolved by #862
