### ISSUE TITLE
[Experimental] Cannot transfer from arbitrary coin balance

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_client_libs#850]
At the moment, we cannot create a transfer from any coin balance as there's no `sk` field. Right now: https://github.com/maidsafe/safe_client_libs/blob/experimental/safe_core/src/client/mod.rs#L275-L282

```rust
fn transfer_coins(
        &self,
        source: XorName,
        destination: XorName,
        amount: Coins,
        transaction_id: Option<u64>,
    ) -> Box<CoreFuture<()>> { 
//... 
}
```

But we need to be able to pass in a `sk` for wallet functionality. So we need something like:

```rust
fn transfer_coins(
        &self,
        from_pk: &PublicKey,
        from_sk: &SecretKey,
        to_pk: &PublicKey,
        transaction_id: ....
        amount: &str,
    ) { 
//... 
}
```

We were assuming the need to pass the keys themselves, if XorName works for Public Key that should be fine (Aside from for `sk`, where we'll need to pass it in)

**Comment by lionel1704** [comment]
Merged into experimental in #871
