### ISSUE TITLE
Create Coin Balance. Preload from another balance missing

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_client_libs#851]
For the CLI we need the ability to create arbitrary coin balances.

These should be able to be preloaded from another balance. OR with `mock` preload `test-coins`.

Currently we can only create balances to fill with test coins.

Wanted:

- Ability to create arbitrary coin balances outside of `mock` mode
- Ability to preload coins from another existing coin balance address.
- Ability to choose to preload `test-coins`

eg (current sig in CLI):
```rust
pub fn create_balance(
        &mut self,
        from_pk: &PublicKeyMock,
        from_sk: &SecretKeyMock,
        new_balance_owner: &PublicKeyMock,
        amount: &str,
    ) 
```

Our current impl is super simple re: coins, so there's no real 'switch' for test vs real coins. Not sure how best this would look for this api.

**Comment by nbaksalyar** [comment]
Implemented in #873
