### ISSUE TITLE
Get balance should accept `sk`

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_client_libs#853]
Getting a `CoinBalance` balance, should be an `ownedGet`. So a `sk` must be passed. 

Currently, no `sk` is accepted by `get_balance`: `fn get_balance(&self, destination: XorName) -> Box<CoreFuture<Coins>>` (https://github.com/maidsafe/safe_client_libs/blob/experimental/safe_core/src/client/mod.rs#L299)

Wanted: Ability to get balance from arbitrary coin balance

**Comment by lionel1704** [comment]
Similar to #843

**Comment by lionel1704** [comment]
Duplicate of #843
