### ISSUE TITLE
SCL API helpers (converting PK/XorUrl/XorName)

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_client_libs#854]
I'm not sure of the current state here. But we should have a 'true' implementation for the conversion of a `PK` to `XorName`.

It looks like the idea is for the API to accept `XorName` mostly.

So, it would be good to have methods to:
- [ ] Convert `PK` to `XorName`
- [ ] ~~Convert XorName` to `PK`~~
- [ ] Convert `XorUrl` to `XorName`
- [ ] Convert `XorName` to `XorUrl`

The last two are probably handled by CAS at some juncture, but I'm not sure where that stands. But feel free to scrub them if they'll be handled elsewhere.

**Comment by lionel1704** [comment]
@joshuef is this issue still valid? The first two conversions are available in safe-nd. The last two tie in with the XorUrl impl. which is in safe-cli.

**Comment by bochaco** [comment]
@lionel1704 can you please point me out which function/helper is available for the first case (PK -> XorName) ?
The second one (XorName -> PK) is impossible so I also doubt it's supported as a helper by safe-nd

**Comment by bochaco** [comment]
Ah..I found the answer to first Q: https://github.com/maidsafe/safe-nd/blob/master/src/public_key.rs#L82

**Comment by nbaksalyar** [comment]
@bochaco, the documentation is now available at https://docs.rs/safe-nd/0.2.1/safe_nd/enum.PublicKey.html too, btw
