### ISSUE TITLE
Missing: mutable_data_delete 

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_client_libs#857]
Currently there's no API implementation for deleting mutable datas.

**Comment by Yoga07** [comment]
Hey Josh, I might have understood this wrong, but is this the one you are looking for? 
>https://github.com/maidsafe/safe_client_libs/blob/1a2a7a44d3775018b432bfe817b138d414cd969a/safe_core/src/client/mod.rs#L479

**Comment by nbaksalyar** [comment]
As @Yoga07 commented, this is already implemented.
