### ISSUE TITLE
Implement account handling as per the Safecoin RFC

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#858]
1. Introduce a notion of `Account` data type (not to be confused with the `Account` structure held by Vaults). This special data type replaces MD with type tag 0 from the previous design: an account is just a location on the network that holds arbitrary data (`Vec<u8>`), with the max. size of 1 MB. It also has a `XorName` as the rest of data types.
2. Support `CreateAccount` and `UpdateAccount` RPCs in mock Vaults. It should respectively create or update the account with the specified destination address.
3. Support `GetAccount` RPC in mock Vault. It should return the `Vec<u8>` data stored within the account.

**Comment by lionel1704** [comment]
Resolved in  #888
