### ISSUE TITLE
Remove the TransferCoins response from safe-nd

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#868]
We do not suppose to have a response variant for `TransferCoins`: the request should be fire-and-forget and we should get the transaction status by sending a `GetTransaction` request.

**Comment by Yoga07** [comment]
Resolved in maidsafe/safe-nd#48

**Comment by nbaksalyar** [comment]
> Resolved in maidsafe/safe-nd#48

Not quite :) The behaviour supposed to be changed in SCL too, i.e. this part: "we should get the transaction status by sending a GetTransaction request", meaning `TransferCoins` should not be sending even the `Mutation(Ok(())` response.

So reopening this issue for now.

**Comment by lionel1704** [comment]
Based on further discussion, we now send a response of the type `Mutation`.
The `GetTransaction` has been removed.
