### ISSUE TITLE
Apps should not be able to send requests to get / mutate auth keys

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_client_libs#896]
Currently, 
- `list_auth_keys`
- `delete_auth_key`
- `insert_auth_key`
are all functions of the `Client` trait. Apps should not be allowed to perform such operations. So this can be removed from the `Client` trait and into the `AuthClient` and `CoreClient` for testing.

**Comment by Yoga07** [comment]
Resolved in #904
