### ISSUE TITLE
Unable to `get_adata_indices` with aunauthed connection (Operation Forbidden)

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_client_libs#899]
Using https://github.com/joshuef/safe-cli/tree/Fix-Integration 

Attempting to fetch latest published append only data, we're seeing `Operation Forbidden` when calling `get_adata_indices` via an aunauthed connection.

To replicate. Pull the above branch and run

`RUST_LOG=safe=trace cargo test --features="mock-network" -- --test-threads=1 calling_safe_files_put_recursive_and_set_dest_path`

## Currently:

`[Error] NetDataError - Failed to get Sequenced Appendable Data indices: CoreError(Operation forbidden - CoreError::OperationForbidden)`

## Wanted: 

All published data should be accessible to unauthed connections.

**Comment by joshuef** [comment]
FYI. This works fine with an authenticated connection.

**Comment by lionel1704** [comment]
Resolved by #903
