### ISSUE TITLE
Errors should not be returned from vault::process_request

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_client_libs#910]
In the `vault::process_request` function there are a few `return` statements that return errors. Error should not be returned in this fashion. They should be returned as a response message corresponding to the incoming request message.

However, in certain cases such as applications sending requests for unsupported operations such as operations related to `AuthKeys`, `DeleteMData` and `DeleteIData`, vaults will identify these requests as malicious and drop them without a response. In such cases, we can use an early return to return a `UnsupportedOperation` error to `process_request`.
In `routing::send` this result should not be `unwrap!`ed, it should be handled greacefully using `map_err(...)?` using an early return to exit without sending a response.

**Comment by m-cat** [comment]
> In the vault::process_request function there are a few return statements that return errors. Error should not be returned in this fashion. They should be returned as a response message corresponding to the incoming request message.

Do you mean the `return`s on this line and a couple more right below it?

https://github.com/maidsafe/safe_client_libs/blob/experimental/safe_core/src/client/mock/vault.rs#L364

**Comment by lionel1704** [comment]
Yes that's right :+1:

**Comment by nbaksalyar** [comment]
Closed via #926
