### ISSUE TITLE
Implement setup_quic_p2p

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_client_libs#911]
The [setup_routing](https://github.com/maidsafe/safe_client_libs/blob/eeb8665d34d31e2e6fab22caf7f1eb4ac5025281/safe_core/src/client/mod.rs#L1900) function should be changed into a `setup_quic_p2p` function. This should take a `NewFullId` and an optional `quic_p2p::Config` field.

The function should use a builder to create a `quic_p2p:QuicP2p` object and connect to a vault.

**Comment by nbaksalyar** [comment]
Closing in favour of #922
