### ISSUE TITLE
Handle exchange of Challenge with a vault

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_client_libs#913]
When connected to a vault, it will send a Challenge that should be signed by the `FullId` and the `Signature` and `PublicId` will be sent as a response. If this challenge is accepted by the vault, clients can now send other requests. 

If a vault does not accept the challenge, it will drop the connection with the client and a `quic_p2p::Event::ConnectionFailure` is received by the client. In such cases, the client will need to re-established the connection.

This can be included in the logic of the `setup_quic_p2p` function

**Comment by nbaksalyar** [comment]
Implemented in #944.
