### ISSUE TITLE
Get requests for published data need not be signed

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_client_libs#916]
When requesting for published data, the request need not be signed. The signature field in the `Message::Request` should be `None`.

For this, add a `signed: bool` field to the `compose_message` function and conditionally set it to None.

In the mock vault, verify that all requests that need a signature are signed and only GETs for published data are allowed to have no signature

**Comment by m-cat** [comment]
Should we modify the `send_new` function to take `is_signed: bool` and conditionally sign the request, and pass in `false` for GETs on published data?

**Comment by lionel1704** [comment]
Seems like a good solution :+1:

**Comment by m-cat** [comment]
Fixed in #943
