### ISSUE TITLE
Add tests to assert that any client/app can GET (Seq/Unseq)Published AppendOnly Data

### ISSUE THREAD

**Issue by Yoga07** [maidsafe/safe_client_libs#919]
Add tests to assert that Anyone(Client/App) in the SAFE Network can access and read a (Seq/Unseq)Published AppendOnly Data.

1. Upload(PUT) a Published AppendOnly Data into the network with an empty Permissions list.
2. Access(GET) the uploaded data from the network with a different Client(who is not present in the Permissions list)
3. Assert if both the uploaded data and the accessed data are the same.

**Comment by lionel1704** [comment]
Resolved by #940
