### ISSUE TITLE
Implement `CreateLoginPacketFor` function in Client

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#928]
Implement a new function to create a new account for someone else, using your own balance. This function should be usable from both App and Authenticator contexts, so it should be added at the `Client` trait level in safe_core and have the following signature:
```rust
use safe_nd::{PublicKey, LoginPacket, Coins, Transaction};

pub fn create_login_packet_for(
  &self,
  new_balance_owner: PublicKey,
  login_packet: LoginPacket,
  amount: Coins
) -> Box<CoreFuture<Transaction>>;
```

The [reference for the flow is available here](https://hackmd.io/@lionel1704/account-creation).

**Comment by lionel1704** [comment]
Resolved by #939
