### ISSUE TITLE
Make handling of zero-length files "do the right thing"

### ISSUE THREAD

**Issue by sprucely** [maidsafe/safe_client_libs#970]
Currently, opening a file in `APPEND` mode assumes that there is existing data to append to and returns an `ERR_NO_SUCH_DATA` if the file happens to not contain any data. I think it would be more intuitive to have the open mode fall back to `OVERWRITE` in such a case rather than returning that error. Or perhaps it could maintain some other internal state that indicates file_close should result in creation of a new file rather than appending to existing data.

**Comment by m-cat** [comment]
Thanks!

**Comment by m-cat** [comment]
Closed via https://github.com/maidsafe/safe_client_libs/pull/1011
