### ISSUE TITLE
Consider updating `Client::full_id`

### ISSUE THREAD

**Issue by m-cat** [maidsafe/safe_client_libs#995]
https://github.com/maidsafe/safe_client_libs/blob/97baefd38965b7a0bc5cdb62f76611b9df8dd90b/safe_core/src/client/mod.rs#L101-L102
We have this `full_id()` function that returns an old, Routing definition of `FullId`. It'd be nice to see if we really use it anywhere, and if not, change this function to return a `SafeKey` instead.

**Comment by nbaksalyar** [comment]
Closed via #997
